rucio-daemons/templates/transmogrifier.yaml
rucio-daemons/values.yaml

Add transmogrifier

---

rucio-daemons/templates/hermes.yaml

Also, can you do the other pull request?

Add useSSL option to Hermes to pick up certificates from secrets

---

logstash/README.md
logstash/my-filebeat.yml
logstash/my-logstash-filter.yml
logstash/my-logstash.yml

Here is the sample of how to configure and start log stash and filebeats.

Logstash examples

---

rucio-server/templates/auth_deployment.yaml
rucio-server/templates/auth_ingress.yaml
rucio-server/templates/auth_service.yaml
rucio-server/values.yaml

Placeholder. Don't merge. Need to parameterize all this stuff

Add parameters needed to get nginx ingress working with SSL passthrough

---

rucio-daemons/templates/abacus-collection-replica.yaml
rucio-daemons/values.yaml

As I mentioned in the meeting, the abacus probably has too much to do to complete for us, but this bit of code does work to get one started. So someone might find it useful.

Make entry for abacus CR daemon

---

rucio-ui/README.md
rucio-ui/values.yaml

No need for webui in front as this is the only ingress in the chart.
also update README.md since a few places still reference "rucio-server"

Make Values match the template. 

---

rucio-daemons/templates/hermes.yaml
rucio-daemons/values.yaml

Also remove a duplicate Hermes section

Allow setting of the hermes broker timeout value.

---

rucio-daemons/templates/tracer-kronos.yaml
rucio-daemons/values.yaml
rucio-server/templates/trace_config.yaml
rucio-server/templates/trace_deployment.yaml
rucio-server/templates/trace_ingress.yaml
rucio-server/templates/trace_service.yaml
rucio-server/values.yaml

Include resource settings for kronos

Add files for dedicated trace servers and kronos daemon

---

rucio-probes/Chart.yaml
rucio-probes/templates/NOTES.txt
rucio-probes/templates/_helpers.tpl
rucio-probes/templates/deployment.yaml
rucio-probes/templates/jobber-configmap.yaml
rucio-probes/templates/secrets.yaml
rucio-probes/values.yaml

Currently they are all run every 15 minutes, but the groundwork is laid to run them on different intervals simply by adding new cron jobs

Add a helm chart for rucio/probes, some of which now work.

---

rucio-probes/templates/deployment.yaml

Latest kubernetes started complaining about this

Fix probes for most recent k8s

---

rucio-daemons/templates/minos.yaml
rucio-daemons/templates/necromancer.yaml
rucio-daemons/values.yaml

Add templates for minos and necromancer

---

rucio-daemons/templates/abacus-account.yaml
rucio-daemons/templates/abacus-collection-replica.yaml
rucio-daemons/templates/abacus-rse.yaml
rucio-daemons/templates/automatix.yaml
rucio-daemons/templates/conveyor-finisher.yaml
rucio-daemons/templates/conveyor-poller.yaml
rucio-daemons/templates/conveyor-receiver.yaml
rucio-daemons/templates/conveyor-submitter.yaml
rucio-daemons/templates/conveyor-throttler.yaml
rucio-daemons/templates/hermes.yaml
rucio-daemons/templates/judge-cleaner.yaml
rucio-daemons/templates/judge-evaluator.yaml
rucio-daemons/templates/judge-injector.yaml
rucio-daemons/templates/judge-repairer.yaml
rucio-daemons/templates/minos-temporary-expiration.yaml
rucio-daemons/templates/minos.yaml
rucio-daemons/templates/necromancer.yaml
rucio-daemons/templates/oauth-manager.yaml
rucio-daemons/templates/reaper.yaml
rucio-daemons/templates/reaper2.yaml
rucio-daemons/templates/servicemonitor.yaml
rucio-daemons/templates/tracer-kronos.yaml
rucio-daemons/templates/transmogrifier.yaml
rucio-daemons/templates/undertaker.yaml
rucio-daemons/values.yaml

Enables pod labels and sets up automatic scraping by prometheus in k8s for pods which produce prometheus metrics

Prometheus annotations

---

rucio-daemons/templates/abacus-account.yaml
rucio-daemons/templates/abacus-collection-replica.yaml
rucio-daemons/templates/abacus-rse.yaml
rucio-daemons/templates/automatix.yaml
rucio-daemons/templates/conveyor-finisher.yaml
rucio-daemons/templates/conveyor-poller.yaml
rucio-daemons/templates/conveyor-receiver.yaml
rucio-daemons/templates/conveyor-submitter.yaml
rucio-daemons/templates/conveyor-throttler.yaml
rucio-daemons/templates/dark-reaper.yaml
rucio-daemons/templates/hermes.yaml
rucio-daemons/templates/judge-cleaner.yaml
rucio-daemons/templates/judge-evaluator.yaml
rucio-daemons/templates/judge-repairer.yaml
rucio-daemons/templates/minos-temporary-expiration.yaml
rucio-daemons/templates/minos.yaml
rucio-daemons/templates/necromancer.yaml
rucio-daemons/templates/oauth-manager.yaml
rucio-daemons/templates/reaper.yaml
rucio-daemons/templates/reaper2.yaml
rucio-daemons/templates/tracer-kronos.yaml
rucio-daemons/templates/transmogrifier.yaml
rucio-daemons/templates/undertaker.yaml
rucio-daemons/values.yaml

This also fixes a bug I introduced with the pod annotations patch, so it should be taken quickly. :-)

Add the dark reaper template

---

rucio-daemons/templates/hermes2.yaml
rucio-daemons/values.yaml

added hermes2 template
added defaults to values.yaml

amendments for hermes2 daemon

---

charts/rucio-probes/templates/deployment.yaml
charts/rucio-probes/values.yaml
charts/rucio-server/templates/auth_deployment.yaml
charts/rucio-server/templates/deployment.yaml
charts/rucio-server/templates/trace_deployment.yaml
charts/rucio-server/values.yaml

Do it the same way it is done in daemons.

servers and probes: rework configuration passing

---

charts/rucio-daemons/Chart.yaml
charts/rucio-daemons/templates/undertaker.yaml

it has to be able to cancel requests of expired dids

mount x509 proxy volume into undertaker

---

charts/rucio-daemons/Chart.yaml
charts/rucio-daemons/templates/cache-consumer.yaml
charts/rucio-daemons/values.yaml

Fortunately this one will stay named "cache-consumer". 
@rcarpa how should we interact with #68? Should we just make this new one the new style of config only?

Add a cache-consumer chart

---

charts/rucio-daemons/Chart.yaml
charts/rucio-daemons/templates/hermes2.yaml

The config volumemount section was duplicated in two places.
One of them being incorrect.

fix template for hermes2

---

charts/rucio-daemons/Chart.yaml
charts/rucio-daemons/templates/automatic-restart-cronjob.yaml

The bug was introduced in daemons chart 1.29.1 with the app label rework

daemons: fix automatic restart

---

charts/rucio-daemons/Chart.yaml
charts/rucio-daemons/README.md
charts/rucio-daemons/templates/renew-fts-cronjob.yaml
charts/rucio-daemons/values.yaml

This reverts commit 5b3a7c1c812c9b3d8128e3c029f6051a99f84bc9.

Revert "enhancement: improve fts cron Fix containers#215 (#125)"

---

charts/rucio-daemons/Chart.yaml
charts/rucio-daemons/README.md
charts/rucio-daemons/templates/renew-fts-cronjob.yaml
charts/rucio-daemons/values.yaml

This is an updated PR from https://github.com/rucio/helm-charts/pull/125
This should fix rucio/containers#215

enhancement: improve fts cron helm debugging Fix rucio/containers#215

---

charts/rucio-server/Chart.yaml
charts/rucio-server/ci/testing-values.yaml
charts/rucio-server/templates/renew-fts-cronjob.yaml
charts/rucio-server/values.yaml

Check the following commit for details:
https://github.com/rucio/helm-charts/commit/d8790d46cc37d8b186ede9eafccd98a8d8fe38a7

servers: support new fts-renewal behavior in servers

---

charts/rucio-server/Chart.yaml
charts/rucio-server/templates/deployment.yaml

otherwise it will not work correctly to set .values.affinity and "local" external policy at the same time

servers: move "local" service antiafinnity setting to existing section

---

charts/rucio-daemons/Chart.yaml
charts/rucio-daemons/templates/undertaker.yaml

was most probably forgotten in a previous commit

daemons: handle useDeprecatedImplicitSecrets

---

charts/rucio-server/Chart.yaml
charts/rucio-server/templates/auth_ingress.yaml
charts/rucio-server/templates/ingress.yaml
charts/rucio-server/templates/trace_ingress.yaml
charts/rucio-server/values.yaml
charts/rucio-ui/Chart.yaml
charts/rucio-ui/templates/ingress.yaml
charts/rucio-ui/values.yaml
charts/rucio-webui/Chart.yaml
charts/rucio-webui/templates/ingress.yaml
charts/rucio-webui/values.yaml

add ingressClassName option

---

charts/rucio-daemons/Chart.yaml
charts/rucio-daemons/ci/testing-values.yaml
charts/rucio-daemons/templates/abacus.yaml
charts/rucio-daemons/templates/automatix.yaml
charts/rucio-daemons/templates/cache-consumer.yaml
charts/rucio-daemons/templates/conveyor.yaml
charts/rucio-daemons/templates/dark-reaper.yaml
charts/rucio-daemons/templates/hermes-legacy.yaml
charts/rucio-daemons/templates/hermes.yaml
charts/rucio-daemons/templates/judge.yaml
charts/rucio-daemons/templates/minos.yaml
charts/rucio-daemons/templates/necromancer.yaml
charts/rucio-daemons/templates/oauth-manager.yaml
charts/rucio-daemons/templates/reaper.yaml
charts/rucio-daemons/templates/renew-fts-cronjob.yaml
charts/rucio-daemons/templates/replica-recoverer.yaml
charts/rucio-daemons/templates/tracer-kronos.yaml
charts/rucio-daemons/templates/transmogrifier.yaml
charts/rucio-daemons/templates/undertaker.yaml
charts/rucio-server/Chart.yaml
charts/rucio-server/ci/testing-values.yaml
charts/rucio-server/templates/deployment.yaml
charts/rucio-server/templates/renew-fts-cronjob.yaml

many components refuse private keys with group/all permissions set.

daemons and servers: support defaultMode in secretMounts

---

charts/rucio-probes/Chart.yaml
charts/rucio-probes/templates/deployment.yaml

We might be the only ones using the helm chart so the only ones noticing this error

Make mount point and where things are being looked for consistent

---

charts/rucio-daemons/Chart.yaml
charts/rucio-daemons/templates/hermes2.yaml

Remove incorrect suffix from hermes2 configuration secret name : Fix #166

---

charts/rucio-daemons/Chart.yaml
charts/rucio-daemons/ci/testing-values.yaml
charts/rucio-daemons/templates/automatix.yaml

make x509up file permission to 0600.

make x509up file permission to 0600.

---

charts/rucio-server/Chart.yaml
charts/rucio-server/templates/deployment.yaml

Being able to use the port name would have been too easy ...

servers: fix separate health check port

---

charts/rucio-webui/Chart.yaml
charts/rucio-webui/templates/service.yaml

nodePort should be under ports, not selectors

webui: fix service spec 

---

charts/rucio-ui/Chart.yaml
charts/rucio-ui/templates/deployment.yaml
charts/rucio-ui/values.yaml

- implemented in the same way as in rucio-server template

ui: allow additionalEnvs for greater flexibility

---

charts/rucio-webui/Chart.yaml
charts/rucio-webui/templates/deployment.yaml

helm chart config updates fails due to duplication of environment variables ( RUCIO_WEBUI_RUCIO_HOST and RUCIO_WEBUI_RUCIO_AUTH_HOST)
```
✗ Helm upgrade failed: cannot patch "webuiint-rucio-webui" with kind Deployment: The order in patch list:
[map[name:RUCIO_WEBUI_OIDC_PROVIDERS value:] map[name:RUCIO_WEBUI_RUCIO_AUTH_HOST value:https://rucio-auth-prod.cern.ch] map[name:RUCIO_WEBUI_RUCIO_AUTH_HOST value:https://rucio-auth-prod.cern.ch] map[name:RUCIO_WEBUI_RUCIO_HOST value:https://rucio-lb-prod.cern.ch] map[name:RUCIO_WEBUI_RUCIO_HOST value:https://rucio-lb-prod.cern.ch] map[name:RUCIO_WEBUI_OIDC_PROVIDER_CERN_AUTHORIZATION_URL value:] map[name:RUCIO_WEBUI_OIDC_PROVIDER_CERN_CLIENT_ID value:] map[name:RUCIO_WEBUI_OIDC_PROVIDER_CERN_CLIENT_SECRET value:] …
```

webui: remove duplicate RUCIO_WEBUI_AUTH_HOST environment variables

---

charts/rucio-daemons/Chart.yaml
charts/rucio-daemons/templates/replica-recoverer-deployment.yaml

@ericvaandering this is needed for https://github.com/dmwm/CMSRucio/issues/806#issuecomment-2370894812

Include missing daemon args for the replica recoverer daemon

---

charts/rucio-server/Chart.yaml
charts/rucio-server/templates/deployment.yaml

server: fix indentation

---

charts/rucio-server/Chart.yaml
charts/rucio-server/templates/_helpers.tpl
charts/rucio-server/templates/deployment.yaml
charts/rucio-server/templates/policy-package-storage.yaml
charts/rucio-server/values.yaml

server: add option to set policy package PVC name via values

---

charts/rucio-ui/Chart.yaml
charts/rucio-ui/templates/service.yaml
charts/rucio-ui/values.yaml

Same as https://github.com/rucio/helm-charts/pull/244 but for ui, which was missing.

[ui]: Add hostname value, optional support for external-dns

---

charts/rucio-daemons/Chart.yaml

https://github.com/rucio/helm-charts/pull/276
Above PR got merged but closed by some weird github bug so the release actions did not get triggered, this PR is intended to trigger the release action.

[daemons]: Increase version to 37.0.2

---

charts/rucio-webui/Chart.yaml
charts/rucio-webui/values.yaml

Add `list_dids_initial_pattern` variable (set by default to empty string) to configure default search pattern (https://github.com/rucio/webui/pull/577)

[webui]: Add `list_dids_initial_pattern` variable

---

charts/rucio-server/Chart.yaml
charts/rucio-server/values.yaml
charts/rucio-ui/Chart.yaml
charts/rucio-ui/templates/deployment.yaml
charts/rucio-webui/Chart.yaml
charts/rucio-webui/templates/deployment.yaml

32 LTS: X-Rucio-Auth-Token -> X-Rucio-Account in logFormat

---

charts/rucio-server/Chart.yaml
charts/rucio-server/values.yaml
charts/rucio-ui/Chart.yaml
charts/rucio-ui/templates/deployment.yaml
charts/rucio-webui/Chart.yaml
charts/rucio-webui/templates/deployment.yaml

35 LTS: X-Rucio-Auth-Token -> X-Rucio-Account in logFormat
