rucio/helm-charts

- rucio-daemons/templates/renew-fts-account.yaml
- rucio-daemons/templates/renew-fts-cronjob.yaml
- rucio-daemons/values.yaml
@tbeerman here is the helm-chart part of the code to add the FTS CronJob part of the renewal process. What do you think? We can change the defaults if you want something better.
> Add the FTS cron job to helm

- rucio-daemons/templates/reaper.yaml
These have to be removed to allow specifying RSEs directly in the config
> Remove quotes around RSE

- rucio-server/templates/auth_deployment.yaml
- rucio-server/templates/deployment.yaml
- rucio-server/values.yaml
This adds an extra log per pod with the error_logs from the server and auth server. You can turn it off by setting the values to False
> Add parameters to expose HTTPD error_log

- rucio-daemons/templates/reaper2.yaml
- rucio-daemons/values.yaml
This adds a new config for reaper2 without mucking with reaper. It seems to work for CMS. Certainly it runs.
I assume at some point we will get rid of "reaper" and rename "reaper2" to reaper.
Also, a new set of helm chart releases with this and the secrets change would be appreciated.
> Add config for reaper2.0

- rucio-server/templates/deployment.yaml
Found a bug that causes resources for the metrics exporter to be inserted into the template output, regardless of if the exporter is enabled.
> Move metrics exporter resources config into the encapsulating block.

- rucio-server/templates/auth_deployment.yaml
Needed for instances of having SSL auth server but not SSL server.
> Do the liveness probe correctly

- rucio-probes/templates/deployment.yaml
- rucio-probes/templates/jobber-configmap.yaml
- rucio-ui/templates/deployment.yaml
A couple of issues I found. One is that jobber-config was not specific enough. And an issue with helm3
> Make explicit jobber config name and fix UI API version

- rucio-probes/templates/jobber-configmap.yaml
- rucio-probes/values.yaml
With the agreement with @dchristidis that CMS probes go in cms/ at least at first, we need a way to run them. This sets up a parallel list of probes to run and you can run probes from any and all VOs.
> Add the ability to turn on VO specific probes

- rucio-daemons/templates/renew-fts-cronjob.yaml
- rucio-daemons/values.yaml
Make the FTS renewal a configurable parameter. There is a race condition in FTS and if you renew from multiple places at the same time you can lose the proxy altogether.
> Make the cron schedule a configurable parameter

- rucio-server/Chart.yaml
- rucio-server/README.md
- rucio-server/templates/deployment.yaml
- rucio-server/templates/renew-fts-account.yaml
- rucio-server/templates/renew-fts-cronjob.yaml
- rucio-server/values.yaml
The writers need to contact fts when update-rule-priority is called.
> add support for fts secrets in rucio-server chart

- rucio-daemons/Chart.yaml
- rucio-server/Chart.yaml
- rucio-ui/Chart.yaml
the correct versions are in gh-pages, because it's the branch used
to server production helm charts.
> Backport versions from gh-pages branch

- rucio-server/Chart.yaml
- rucio-server/templates/deployment.yaml
Otherwise, it will try to mount secrets which don't exist.
> rucio-server: only mount x509 key and ca sercrets if fts renewal enabled

- charts/rucio-server/Chart.yaml
- charts/rucio-server/templates/deployment.yaml
otherwise the generated yaml is invalid
> rucio-server: fix jinja substitution eol stripping

- charts/rucio-server/templates/auth_deployment.yaml
Since 1.26, the exposed endpoint is controlled through config. This PR adds a config item to expose `auth` and `ping` endpoint in the auth server.
> Add auth,ping endpoint for auth endpoint

- charts/rucio-daemons/templates/conveyor-finisher.yaml
- charts/rucio-daemons/templates/conveyor-poller.yaml
- charts/rucio-daemons/templates/conveyor-preparer.yaml
- charts/rucio-daemons/templates/conveyor-receiver.yaml
- charts/rucio-daemons/templates/conveyor-stager.yaml
- charts/rucio-daemons/templates/conveyor-submitter.yaml
- charts/rucio-daemons/templates/conveyor-throttler.yaml
- charts/rucio-daemons/values.yaml
Each daemon will now have its own config secret with two sections: "common" and
"component". The common is the same for all daemons. I initially thought about having
a separate "common" kube secret shared among all daemons, but changed my mind.
I consider that having two secrets makes the configuration flow more complex while
the benefit (no duplication) is small.
As long as values.exportConfigToEnv==True, the change must not impact existing
deployments. The new secrets will be generated in kube, mounter into containers,
but not used by rucio.
The associated change in rucio/containers must be integrated into containers before
setting this variable to False.
If the new behavior is accepted, all daemons and servers will have to be updated.
I also vote for breaking the reverse compatibility …
> daemons: rework configuration passing in conveyor

- charts/rucio-server/Chart.yaml
- charts/rucio-server/templates/auth_deployment.yaml
- charts/rucio-server/templates/deployment.yaml
- charts/rucio-server/templates/trace_deployment.yaml
It is inconsistency with unknown origin. Other helm-charts only allow
usage of supPath (singular), but servers only allow it at plural.
Also, subPaths is not documented anywhere. Even the server chart
documentation shows the singular form.
For a transitory period, allow usage of both forms, but I suggest to
completely remove support for the plural form latter.
> servers: support both subPath and subPaths in additionalSecrets. Closes #70

- charts/rucio-server/Chart.yaml
- charts/rucio-server/templates/auth_deployment.yaml
- charts/rucio-server/templates/auth_servicemonitor.yaml
- charts/rucio-server/templates/deployment.yaml
- charts/rucio-server/templates/servicemonitor.yaml
- charts/rucio-server/templates/trace_deployment.yaml
- charts/rucio-server/templates/trace_servicemonitor.yaml
- charts/rucio-server/values.yaml
Latest containers are now built with the possibility to export
prometheus metrics on a separate port:
https://github.com/rucio/containers/pull/180
This PR ensures that the correct ENV variable is set to trigger
this behavior in servers and that the prometheus-operator
ServiceMonitor CRD is configured to automatically scrape that
endpoint.
> servers: expose and collect server prometheus metrics

- charts/rucio-server/Chart.yaml
- charts/rucio-server/templates/_helpers.tpl
- charts/rucio-server/templates/auth_ingress.yaml
- charts/rucio-server/templates/ingress.yaml
- charts/rucio-server/templates/trace_ingress.yaml
- charts/rucio-ui/Chart.yaml
- charts/rucio-ui/templates/_helpers.tpl
- charts/rucio-ui/templates/ingress.yaml
The stable ingress api is available since kubernetes 1.19 (August 26, 2020).
The old beta api is deprecated in 1.22.
> servers & ui: support kube 1.22+ in ingress. Closes #80

- charts/rucio-daemons/Chart.yaml
- charts/rucio-daemons/templates/renew-fts-cronjob.yaml
- charts/rucio-server/Chart.yaml
- charts/rucio-server/templates/renew-fts-cronjob.yaml
add a job which will run on helm install and generate the initial
proxy from the longproxy. This way, containers could start after
installation without failing because of missing 509 proxy.
I factorize the job spec into a template and use it in both
cronjob and install hook (job).
> daemons & servers: add helm install hook to generate fts proxy

- charts/rucio-server/templates/auth_ingress.yaml
- charts/rucio-server/templates/trace_ingress.yaml
Also add the changes back to 1.26 for me. :)
> Fix references to incorrect host values for Ingresses. Closes #92

- charts/rucio-server/Chart.yaml
- charts/rucio-server/values.yaml
Add a variable for the legacy DN format. With a change to the containers, this could be back ported to LTS releases if needed
> Variable for Legacy DN format

- charts/rucio-daemons/Chart.yaml
- charts/rucio-daemons/templates/hermes.yaml
- charts/rucio-daemons/values.yaml
It wasn't used by hermes, so got removed from rucio in last release.
Effectively breaking helm charts
> daemons: use sleepTime instead of delay in hermes

- charts/rucio-ui/Chart.yaml
- charts/rucio-ui/values.yaml
Similar to https://github.com/rucio/helm-charts/pull/99 we need the same setting in the WebUI
Needs companion PR for containers to be functional https://github.com/rucio/containers/pull/203
> Add support for the LegacyDN setting for the WebUI too.

- charts/rucio-ui/Chart.yaml
- charts/rucio-ui/templates/deployment.yaml
This is an oversight, I thought we are already populating environment variables since the setting was there in the helm chart. Lifted from rucio-server.
> Mistakenly assumed we were moving these to ENV variables already

- charts/rucio-server/Chart.yaml
- charts/rucio-server/templates/auth_deployment.yaml
- charts/rucio-server/templates/automatic-restart-cronjob.yaml
- charts/rucio-server/templates/renew-fts-cronjob.yaml
- charts/rucio-server/values.yaml
Some resources (namely, [NRP](https://dash.nrp-nautilus.io/) ) have strict requirements for all containers to explicitly request resources.
This PR adds resource requests for the FTS renewal and server restart cronjobs.  It also adds a resource request for the error exporter in the authentication server.
> Add resource requests for CronJobs

- charts/rucio-daemons/Chart.yaml
- charts/rucio-daemons/templates/replica-recoverer.yaml
This patch introduce an helm-chart for the new `replica-recoverer` daemon
> Add replica-recoverer chart : Closes #78

- charts/rucio-server/templates/NOTES.txt
- charts/rucio-ui/templates/NOTES.txt
While running some of the commands which are giving by notes.txt, those are failing because of namespace parameter is not there for some of the commands.
> Adding namespace parameter to the missing commands in notes

- charts/rucio-daemons/Chart.yaml
- charts/rucio-daemons/templates/_helpers.tpl
- charts/rucio-daemons/templates/automatic-restart-cronjob.yaml
- charts/rucio-daemons/templates/renew-fts-cronjob.yaml
- charts/rucio-server/Chart.yaml
- charts/rucio-server/templates/_helpers.tpl
- charts/rucio-server/templates/auth_ingress.yaml
- charts/rucio-server/templates/automatic-restart-cronjob.yaml
- charts/rucio-server/templates/ingress.yaml
- charts/rucio-server/templates/renew-fts-cronjob.yaml
- charts/rucio-server/templates/trace_ingress.yaml
- charts/rucio-ui/Chart.yaml
- charts/rucio-ui/templates/_helpers.tpl
- charts/rucio-ui/templates/ingress.yaml
The old API is deprecated already and was removed in 1.25: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#cronjob-v125
> all: make CronJob compatible with k8s 1.25+. Closes #118

- charts/rucio-daemons/Chart.yaml
- charts/rucio-daemons/templates/servicemonitor.yaml
- charts/rucio-daemons/values.yaml
- charts/rucio-server/Chart.yaml
- charts/rucio-server/templates/auth_servicemonitor.yaml
- charts/rucio-server/templates/servicemonitor.yaml
- charts/rucio-server/templates/trace_servicemonitor.yaml
- charts/rucio-server/values.yaml
This is to perform transformation on metrics before ingestion to prometheus. For example, to mark mertrics which will be forwarded upstream for longer-term storage.
> servers & daemons: support relabeling for servicemonitor

- .github/workflows/lint-test.yml
- README.md
This PR fixes #95 by implementing a new helm and lint test workflow in GitHub Actions.
It would probably be a good idea to set this workflow as a merge requirement.
> enhancement: add lint test workflow for charts fix #95

- charts/rucio-server/Chart.yaml
- charts/rucio-server/templates/deployment.yaml
- charts/rucio-server/values.yaml
I need to pass the node IP inside the pod for the servers which use the proxy protocol. This is to allow traffic originating from this IP to not use the proxy protocol. Otherwise the health checks (readiness/liviness) probes coming from the kubelet fail.
> servers: support setting additional env values

- charts/rucio-daemons/Chart.yaml
- charts/rucio-daemons/templates/conveyor.yaml
due to merging all conveyor into one, the rendered result doesn't have the correct separator between different components.
> daemons: fix conveyor template

- charts/rucio-server/Chart.yaml
- charts/rucio-server/templates/auth_deployment.yaml
- charts/rucio-server/templates/deployment.yaml
- charts/rucio-server/templates/secrets.yaml
- charts/rucio-server/templates/trace_deployment.yaml
Check the following commit for details:
https://github.com/rucio/helm-charts/commit/8ab83a60e427295fe126cb25d39b977a30471aca
> servers: deprecate implicit ca and proxy volume mounts

- charts/rucio-server/Chart.yaml
- charts/rucio-server/templates/auth_deployment.yaml
- charts/rucio-server/templates/deployment.yaml
- charts/rucio-server/templates/trace_deployment.yaml
- charts/rucio-server/values.yaml
To avoid sending traffic to pods which didn't yet fully start.
> servers: add readinessProbe

- charts/rucio-daemons/Chart.yaml
- charts/rucio-daemons/ci/testing-values.yaml
- charts/rucio-daemons/templates/abacus-account.yaml
- charts/rucio-daemons/templates/abacus-collection-replica.yaml
- charts/rucio-daemons/templates/abacus-rse.yaml
- charts/rucio-daemons/templates/automatix.yaml
- charts/rucio-daemons/templates/cache-consumer.yaml
- charts/rucio-daemons/templates/conveyor.yaml
- charts/rucio-daemons/templates/dark-reaper.yaml
- charts/rucio-daemons/templates/hermes.yaml
- charts/rucio-daemons/templates/hermes2.yaml
- charts/rucio-daemons/templates/judge-cleaner.yaml
- charts/rucio-daemons/templates/judge-evaluator.yaml
- charts/rucio-daemons/templates/judge-injector.yaml
- charts/rucio-daemons/templates/judge-repairer.yaml
- charts/rucio-daemons/templates/minos-temporary-expiration.yaml
- charts/rucio-daemons/templates/minos.yaml
- charts/rucio-daemons/templates/necromancer.yaml
- charts/rucio-daemons/templates/oauth-manager.yaml
- charts/rucio-daemons/templates/reaper.yaml
- charts/rucio-daemons/templates/replica-recoverer.yaml
- charts/rucio-daemons/templates/tracer-kronos.yaml
- charts/rucio-daemons/templates/transmogrifier.yaml
- charts/rucio-daemons/templates/undertaker.yaml
- charts/rucio-daemons/values.yaml
It will take precedence over the global tag. This can be useful during transition to alma9, when some components may have to be left behind for some time (reaper for example).
> daemons: support custom image tag in each component

- charts/rucio-server/Chart.yaml
- charts/rucio-server/ci/testing-values.yaml
- charts/rucio-server/templates/deployment.yaml
- charts/rucio-server/templates/renew-fts-cronjob.yaml
- charts/rucio-server/values.yaml
Similarly to secretMounts, add a higher-level primitive 'hostPathMounts' which allows the user to mount a path from the kubernetes host into the container.
> servers: support mounting host paths

- charts/rucio-server/Chart.yaml
- charts/rucio-server/templates/renew-fts-cronjob.yaml
We should prefer the override from the fts cronjob over the global value, not the opposite. Also, allow to override with an empty array.
> servers: fix hostPathMounts override direction

- charts/rucio-ui/Chart.yaml
- charts/rucio-ui/templates/deployment.yaml
- charts/rucio-ui/values.yaml
> WebUI: Add useDeprecatedImplicitSecrets to legacy webui chart #174

- charts/rucio-server/Chart.yaml
- charts/rucio-server/templates/deployment.yaml
This will allow health checks to work even if the proxy protocol is enabled on the main port.
> servers: use separate port for health checks

- charts/rucio-ui/Chart.yaml
- charts/rucio-ui/templates/deployment.yaml
- charts/rucio-ui/templates/ingress.yaml
- charts/rucio-ui/templates/service.yaml
- charts/rucio-ui/values.yaml
The `rucio-ui` containers were recently updated in https://github.com/rucio/containers/pull/296. The update involved restructuring the Jinja2 templates that generate the httpd config.
This PR reflects back the changes in containers in the helm charts for rucio-ui
> Fixes for Rucio UI ( not WebUI) 33.x charts

- charts/rucio-webui/Chart.yaml
- charts/rucio-webui/README.md
- charts/rucio-webui/templates/deployment.yaml
- charts/rucio-webui/templates/service.yaml
- charts/rucio-webui/values.yaml
Modifies the existing `rucio-webui` helm chart to incorporate the NextJS application
> webui: add helm charts for 33.x and future releases

- charts/rucio-ui/Chart.yaml
- charts/rucio-ui/templates/service.yaml
move the port spec into the port section ( it was in the selector section earlier)
> ui: fix NodePort service spec

- charts/rucio-webui/Chart.yaml
- charts/rucio-webui/templates/deployment.yaml
- charts/rucio-webui/templates/ingress.yaml
- charts/rucio-webui/values.yaml
Hi,
- The addition of `.Values.useDeprecatedImplicitSecrets`
This change will add the possibility of having non-hostpath-mounted certificates, but instead have them be managed by the user (through kubernetes for example). This option is already present in the `rucio-server` chart, and I think it is very usefull for the webui as well
- The addition of  `.Values.ingress.tls` 
This change will allow the user to have tls ingress to the webui cluster. This option is also copied from how its done on the `rucio-server`.
Kind Regards,
Victor
> Improvements for webui chart

- charts/rucio-ui/Chart.yaml
- charts/rucio-ui/templates/deployment.yaml
- charts/rucio-ui/values.yaml
- charts/rucio-webui/Chart.yaml
- charts/rucio-webui/templates/service.yaml
Allow .Values.hostPathMount to mount volumes from host machines into pods. Useful for mounting certificates and CRLs directly to `/etc/grid-security/certificates` inside pods
> UI hostpath mounts

- charts/rucio-webui/Chart.yaml
- charts/rucio-webui/values.yaml
In order to support DID schemas that use special characters like "/", a new configuration option has been added to the new webui to enable or disable this functionality.
In cases where DID schemas use any such special characters,  the Apache configuration of the Rucio Server most likely uses "AllowEncodedSlashes" or "AllowEncode" directives.
The new `params_encoding_enabled ` in the helm chart config of the Rucio WebUI tells the webui to encode the URI parameters when requests are sent out to the rucio server
> webui: url encoding option

- charts/rucio-daemons/Chart.yaml
- charts/rucio-daemons/templates/renew-fts-cronjob.yaml
- charts/rucio-daemons/values.yaml
Closes #220 
Tagging @ericvaandering as CMS might be impacted directly.
- Added conditional statement that checks for `"none"` option in `values.yaml`, and if so does not declare `RUCIO_VO` and `RUCIO_FTS_VOMS`. 
- Changed default values for `vo` and `voms` to `"none"`.
By running 
```sh
helm template . --kube-version 1.31 --debug --values values.yaml --show-only templates/renew-fts-cronjob.yaml
```
We get: 
```yaml
env:
- name: RUCIO_FTS_SCRIPT
value: "default"
- name: RUCIO_FTS_VO_COUNT
value: "1"
- name: RUCIO_FTS_VO_0
value: none
- name: RUCIO_FTS_VOMS_0
value: none
```
In which are correctly missing `RUCIO_VO` and `RUCIO_FTS_VOMS`.
Should we avoid creating also `RUCIO_FTS_VO/VOMS_{{ $key }}`?
> Enabling VO-agnostic FTS proxy production

- .gitignore
- charts/rucio-server/Chart.yaml
- charts/rucio-server/templates/deployment.yaml
- charts/rucio-server/templates/policy-package-storage.yaml
- charts/rucio-server/values.yaml
Initial PR to add policy package support to the Rucio server.
Current questions:
- Does the `|`'d command work when using multiple packages? (edit: it does)
> Policy package support for Rucio server

- charts/rucio-daemons/Chart.yaml
- charts/rucio-daemons/templates/abacus-deployment.yaml
- charts/rucio-daemons/templates/automatic-restart-account.yaml
- charts/rucio-daemons/templates/automatic-restart-cronjob.yaml
- charts/rucio-daemons/templates/automatix-deployment.yaml
- charts/rucio-daemons/templates/cache-consumer-deployment.yaml
- charts/rucio-daemons/templates/conveyor-deployment.yaml
- charts/rucio-daemons/templates/dark-reaper-deployment.yaml
- charts/rucio-daemons/templates/hermes-deployment.yaml
- charts/rucio-daemons/templates/hermes-legacy-deployment.yaml
- charts/rucio-daemons/templates/judge-deployment.yaml
- charts/rucio-daemons/templates/minos-deployment.yaml
- charts/rucio-daemons/templates/necromancer-deployment.yaml
- charts/rucio-daemons/templates/oauth-manager-deployment.yaml
- charts/rucio-daemons/templates/reaper-deployment.yaml
- charts/rucio-daemons/templates/renew-fts-account.yaml
- charts/rucio-daemons/templates/renew-fts-cronjob.yaml
- charts/rucio-daemons/templates/replica-recoverer-deployment.yaml
- charts/rucio-daemons/templates/tracer-kronos-deployment.yaml
- charts/rucio-daemons/templates/transmogrifier-deployment.yaml
- charts/rucio-daemons/templates/undertaker-deployment.yaml
- charts/rucio-server/Chart.yaml
- charts/rucio-server/templates/automatic-restart-account.yaml
- charts/rucio-server/templates/automatic-restart-cronjob.yaml
- charts/rucio-server/templates/renew-fts-account.yaml
- charts/rucio-server/templates/renew-fts-cronjob.yaml
Closes #230
Also mostly overrides the changes introduced in https://github.com/rucio/helm-charts/pull/227.
More details in issue.
Using `rucio.fullname` instead of the release name provides (IMHO) better support when using the full name override option as all names will have a name independent of the release name.
Due to the definition of `rucio.fullname` the default behaviour should remain the same.
> [Server, Daemons]: broader use `rucio.fullname` in names

- charts/rucio-server/Chart.yaml
- charts/rucio-server/templates/service.yaml
- charts/rucio-server/values.yaml
- charts/rucio-webui/Chart.yaml
- charts/rucio-webui/templates/service.yaml
- charts/rucio-webui/values.yaml
Closes https://github.com/rucio/helm-charts/issues/248
We have been trying `external-dns` to manage the dns records for our services with good results.
`external-dns` uses annotations in the services in order to work.
Getting the correct configuration with the current rucio charts was not straightforward and it required having duplicated config values (you don't want to hardcode the hostname in multiple places). This can be fixed by adding a configuration value named `hostname` which then can be referenced elsewhere.
The way to enable `external-dns` is via a disabled-by-default flag named `useExternalDNS` which adds the necessary annotations. While the current design which allows arbitrary annotations works in theory, it requires duplication of values.
I refactored the section related to …
> [server, webui]: Add `hostname` value, optional support for `external-dns`

- charts/rucio-daemons/Chart.yaml
- charts/rucio-daemons/templates/renew-fts-cronjob.yaml
- charts/rucio-daemons/values.yaml
- charts/rucio-server/Chart.yaml
- charts/rucio-server/templates/deployment.yaml
- charts/rucio-server/values.yaml
- charts/rucio-webui/Chart.yaml
- charts/rucio-webui/templates/deployment.yaml
- charts/rucio-webui/values.yaml
Closes https://github.com/rucio/helm-charts/issues/246
Add new field `tlsSecretName` (unset by default) which can be used to point to a tls secret which will then be used to setup the public/private keys for tls.
I think this provides a cleaner approach compared to asking the user to mount some secrets into some specific paths.
Before this change you would need to do:
```
secretMounts:
- secretFullName: rucio-tls-host-cert
mountPath: /etc/grid-security/hostcert.pem
subPath: tls.crt
- secretFullName: rucio-tls-host-key
mountPath: /etc/grid-security/hostkey.pem
subPath: tls.key
```
After this can optionally be condensed into:
```
tlsSecretName: rucio-tls-host
```
Besides the reduced lines of code needed, now (IMHO) it's easier for a new user to figure out how to setup tls from looking at …
> [server, webui, daemons]: Support setting tls secrets by name

- charts/rucio-daemons/Chart.yaml
- charts/rucio-daemons/templates/abacus-deployment.yaml
- charts/rucio-daemons/templates/automatix-deployment.yaml
- charts/rucio-daemons/templates/cache-consumer-deployment.yaml
- charts/rucio-daemons/templates/conveyor-deployment.yaml
- charts/rucio-daemons/templates/dark-reaper-deployment.yaml
- charts/rucio-daemons/templates/hermes-deployment.yaml
- charts/rucio-daemons/templates/hermes-legacy-deployment.yaml
- charts/rucio-daemons/templates/judge-deployment.yaml
- charts/rucio-daemons/templates/minos-deployment.yaml
- charts/rucio-daemons/templates/necromancer-deployment.yaml
- charts/rucio-daemons/templates/oauth-manager-deployment.yaml
- charts/rucio-daemons/templates/reaper-deployment.yaml
- charts/rucio-daemons/templates/replica-recoverer-deployment.yaml
- charts/rucio-daemons/templates/tracer-kronos-deployment.yaml
- charts/rucio-daemons/templates/transmogrifier-deployment.yaml
- charts/rucio-daemons/templates/undertaker-deployment.yaml
- charts/rucio-daemons/values.yaml
The change introduces an optional way to add environment variables shared between all daemons.
This reduces code duplication for shared envs between daemons such as database configuration etc.
Also closes https://github.com/rucio/helm-charts/issues/247 since the main motivation of the issue was that the env variable approach resulted in too much code duplication. I don't think we need another way to configure the drabase anymore.
> [daemons]: Option to have shared env variables between all daemons

- charts/rucio-daemons/Chart.yaml
- charts/rucio-daemons/templates/abacus-deployment.yaml
- charts/rucio-daemons/templates/automatix-deployment.yaml
- charts/rucio-daemons/templates/cache-consumer-deployment.yaml
- charts/rucio-daemons/templates/conveyor-deployment.yaml
- charts/rucio-daemons/templates/dark-reaper-deployment.yaml
- charts/rucio-daemons/templates/hermes-deployment.yaml
- charts/rucio-daemons/templates/hermes-legacy-deployment.yaml
- charts/rucio-daemons/templates/judge-deployment.yaml
- charts/rucio-daemons/templates/minos-deployment.yaml
- charts/rucio-daemons/templates/necromancer-deployment.yaml
- charts/rucio-daemons/templates/oauth-manager-deployment.yaml
- charts/rucio-daemons/templates/reaper-deployment.yaml
- charts/rucio-daemons/templates/replica-recoverer-deployment.yaml
- charts/rucio-daemons/templates/tracer-kronos-deployment.yaml
- charts/rucio-daemons/templates/transmogrifier-deployment.yaml
- charts/rucio-daemons/templates/undertaker-deployment.yaml
- charts/rucio-daemons/values.yaml
- charts/rucio-server/Chart.yaml
- charts/rucio-server/templates/deployment.yaml
- charts/rucio-server/values.yaml
- charts/rucio-webui/Chart.yaml
- charts/rucio-webui/templates/deployment.yaml
- charts/rucio-webui/values.yaml
Closes #250 
Via annotations one can configure reloader to reload the related service whenever a change to a secret or configmap happens:
```
deploymentAnnotations:
reloader.stakater.com/auto: "true"
```
By default deployments will be reloaded whenever any secret/map mounted on them is changed. This can be configured with great granularity via annotations either in the deployment or secrets (you only want to reload whenever one particular secret changes, etc.). I think the default behaviour is good enough.
Via this strategy the server will reload whenever the policy package is updated, or daemons will reload whenever the certificate is updated by the cronjob.
> Add optional deployment annotations

- charts/rucio-server/Chart.yaml
- charts/rucio-server/templates/deployment.yaml
- charts/rucio-server/values.yaml
By setting
```
policyPackages:
ephemeralVolume: true
```
the policy package will be installed in a ephmeral volume, meaning that it will be reinstalled every time the pod restarts.
The upside of this approach is that we do not need PV/PVC so we can run it on a k8s cluster without any storage.
> [server]: Add optional support of policy package in ephemeral volume

- charts/rucio-daemons/Chart.yaml
- charts/rucio-daemons/templates/policy-packages-init.yaml
- charts/rucio-server/Chart.yaml
- charts/rucio-server/templates/deployment.yaml
- charts/rucio-ui/Chart.yaml
- charts/rucio-ui/templates/deployment.yaml
- charts/rucio-webui/Chart.yaml
- charts/rucio-webui/templates/deployment.yaml
Fix #289 
starting with `atlas_rucio_policy_package==0.4.0`
- first run
```
Collecting atlas_rucio_policy_package==0.4.0
Downloading atlas_rucio_policy_package-0.4.0-py3-none-any.whl (23 kB)
Installing collected packages: atlas-rucio-policy-package
Successfully installed atlas-rucio-policy-package-0.4.0
```
- in server
```
>>> import atlas_rucio_policy_package
>>> atlas_rucio_policy_package
<module 'atlas_rucio_policy_package' from '/opt/policy_packages/atlas_rucio_policy_package/__init__.py'>
>>> print(version("atlas_rucio_policy_package"))
>>> from importlib.metadata import version
>>> print(version("atlas_rucio_policy_package"))
0.4.0
```
modified to
```
- moduleName: atlas_rucio_policy_package
requirement: atlas_rucio_policy_package==0.6.0
version: 0.6.0
```
```
helm upgrade -f …
```
> Clear policy package path before upgrading

- charts/rucio-server/Chart.yaml
- charts/rucio-server/templates/deployment.yaml
- charts/rucio-server/values.yaml
In CTAO, we need to avoid getting images from dockerhub due to their restrictive pull limits.
We have our own images in a harbor and a proxy for dockerhub there as well, however, these are different namespaces and the current chart doesn't allow us to get 
- the busybox image from harbor.cta-observatory.org/proxy_cache/busybox
- the rucio images from harbor.cta-observatory.org/dpps/bdms-rucio-server
This adds the missing values configuration to enable this.
> Make httpd error log image configurable
